#!/usr/bin/env bash
set -e
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    CREATE USER $API_CLIENT_USER WITH PASSWORD '$API_CLIENT_PASS';

    GRANT SELECT, INSERT, UPDATE ON users        TO $API_CLIENT_USER;
    GRANT SELECT, INSERT, UPDATE ON sessions     TO $API_CLIENT_USER;
    GRANT SELECT, INSERT, UPDATE ON vault        TO $API_CLIENT_USER;
    GRANT SELECT, INSERT, UPDATE ON vault_entry  TO $API_CLIENT_USER;
    GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO $API_CLIENT_USER;

    GRANT INSERT ON audit_log_entry TO $API_CLIENT_USER;

    CREATE USER $DASHBOARD_CLIENT_USER WITH PASSWORD '$DASHBOARD_CLIENT_PASSWORD';

    GRANT SELECT ON users           TO $DASHBOARD_CLIENT_USER;
    GRANT SELECT ON sessions        TO $DASHBOARD_CLIENT_USER;
    GRANT SELECT ON vault           TO $DASHBOARD_CLIENT_USER;
    GRANT SELECT ON vault_entry     TO $DASHBOARD_CLIENT_USER;
    GRANT SELECT ON audit_log_entry TO $DASHBOARD_CLIENT_USER;

EOSQL
